ffrm/ffrm/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('rm/', include('rmapp.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ffrm/rmapp/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('upload/<int:client_doc_id>/', views.documentRequest, name='documentRequest'),
]

ffrm/rmapp/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class RelMan(models.Model):
    rm_name = models.CharField(max_length=200, verbose_name='Name')

    def __str__(self):
        return self.rm_name

    class Meta:
        verbose_name = 'Relationship Manager'

class Client(models.Model):
    c_name = models.CharField(max_length=200, verbose_name='Name')
    c_phone = models.CharField(max_length=10, verbose_name='Phone')
    c_email = models.CharField(max_length=200, verbose_name='Email')
    c_rm = models.ForeignKey(RelMan, on_delete=models.CASCADE, verbose_name='Relationship Manager')

    def __str__(self):
        return self.c_name
    
    class Meta:
        verbose_name = 'Client'

class ClientDoc(models.Model):
    d_desc = models.CharField(max_length=200, verbose_name='Description')
    d_created = models.DateTimeField(verbose_name='Uploaded', null=True, blank=True)
    d_file = models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='File', null=True, blank=True)
    d_client = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name='Client')

    def __str__(self):
        return self.d_desc
    
    class Meta:
        verbose_name = 'Client Document'

    def get_upload_link(self):
        return '%s' % (reverse('documentRequest', kwargs={'client_doc_id': self.id}))

ffrm/rmapp/forms.py
from django import forms
from .models import ClientDoc

class UploadClientDocForm(forms.ModelForm):
    class Meta:
        model = ClientDoc
        fields = ['d_file']

ffrm/rmapp/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.utils import timezone
from rmapp.forms import UploadClientDocForm
from rmapp.models import ClientDoc

# Create your views here.

def index(request):
    return HttpResponse("Hello, world. You're at the Future Forex Relationship Manager index.")

def documentRequest(request, client_doc_id):
    client_doc = ClientDoc.objects.get(pk=client_doc_id)
    form = UploadClientDocForm()
    success = False;
    error_message = ''

    if client_doc.d_file:
        success = True;

    if request.method == 'POST':
        form = UploadClientDocForm(request.POST, request.FILES)

        if form.is_valid():
            if "d_file" not in request.FILES:
                error_message = 'You need to upload a file.'
            else: 
                client_doc.d_file = request.FILES['d_file']
                client_doc.d_created = timezone.now()
                client_doc.save()

                success = True        

    return render(request, 'upload.html', {'form': form, 'client_doc': client_doc, 'success': success, 'error_message': error_message})

ffrm/rmapp/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF" crossorigin="anonymous">

    <link href="{% static 'custom.css' %}" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">
          <img src="{% static 'logo.png' %}" alt="Relationship Manager" width="30" height="24">
          Relationship Management
        </a>
      </div>
    </nav>

    <div class="container-fluid">
      {% block content %}{% endblock %}
    </div>
    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous"></script>
  </body>
</html>

ffrm/rmapp/templates/upload.html
{% extends "base.html" %}

{% block title %}Upload Document{% endblock %}

{% block content %}
{% if success%}
    <div class="row">
        <div class="col">
            <div class="thank-you-wrapper">
                <div class="alert alert-success">Thank you for uploading: {{client_doc.d_desc}}</div>
            </div>
        </div>
    </div>
{% else %}
<div class="row">
    <div class="col">
        <div class="upload-form-wrapper">
            <h3>Please upload: {{client_doc.d_desc}}</h3>

            <form action="" method="post" enctype="multipart/form-data" class="form">
                {% csrf_token %}

                {% for field in form %}
                    <div class="mb-3">
                        <label for="id_d_file" class="form-label">File</label>
                        <input type="file" id="id_d_file" name="d_file">

                        {% if error_message %}
                        <div class="field-error-wrapper">
                            <div class="alert alert-danger">{{ error_message }}</div>
                        </div>
                        {% endif %}
                    </div>
                {% endfor %}

                <div class="mb-3">
                    <input type="submit" value="Upload" class="btn btn-sm btn-success">
                </div>
            </form>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}